Add draft release notes for first RC of 1.5.0.
apache/guacamole-website pull request #110
Opened 2023-02-13 06:51 UTC by mike-jumper

2023-02-13 12:36 UTC, necouchman requested changes
I know it's still in draft mode, but looks pretty good. One minor nitpick - missing space - noted below.

2023-02-13 12:36 UTC, necouchman commented on _releases/1.5.0.md
> + * {:.bug} An improper locking bug(e.g., resource leak) due to unreleased lock ([GUACAMOLE-1416](https://issues.apache.org/jira/browse/GUACAMOLE-1416))
#nitpick - Should probably be a space between "bug" and the opening parenthesis.

2023-02-13 21:50 UTC, mike-jumper commented on _releases/1.5.0.md
> + * {:.bug} An improper locking bug(e.g., resource leak) due to unreleased lock ([GUACAMOLE-1416](https://issues.apache.org/jira/browse/GUACAMOLE-1416))
True - I'll fix that. These were just automatically scraped from JIRA. ;)

2023-02-14 01:21 UTC, mike-jumper commented
Un-drafted!

2023-02-14 02:13 UTC, jmuehlner commented
@necouchman Github still shows that you have requested changes - can you confirm that your concerns have been addressed?

2023-02-14 03:02 UTC, necouchman approved these changes
All good, here.

2023-02-14 23:05 UTC, merged