Create etes_gmbh.md
apache/guacamole-website pull request #148
Opened 2024-08-13 12:40 UTC by ETES-Stuttgart

Adding ETES GmbH as Commercial Support

2024-08-13 16:45 UTC, mike-jumper requested changes

2024-08-13 16:45 UTC, mike-jumper commented on _companies/etes_gmbh.md
> +logo: https://www.etes.de/files/etes/ETES_Logo_200px.png
Please:

1. Add the desired logo to `images/companies/`.
2. Point to that path for the logo instead of this remote URL.

For example, see the structure of the established `.md` files for other support companies and their corresponding logos:

* https://github.com/apache/guacamole-website/blob/main/_companies/
* https://github.com/apache/guacamole-website/blob/main/images/companies/

2024-08-14 04:35 UTC, ETES-Stuttgart commented on _companies/etes_gmbh.md
> +logo: https://www.etes.de/files/etes/ETES_Logo_200px.png
Hi Mike,
thank you for your hint. I've changed the pull request right now.

Best regards
Simon

2024-08-14 06:53 UTC, mike-jumper requested changes
Please also combine these commits into a single commit with a high-level message describing the change being made. For example, see the last commit messages for the `.md` files of other companies already beneath `_companies/`:
 
https://github.com/apache/guacamole-website/tree/main/_companies

Otherwise, looks good to me.

2024-08-14 06:53 UTC, mike-jumper commented on images/companies/etes-gmbh.png
Please resize this image such that it is no larger than 144x144 (see https://guacamole.apache.org/support/#requesting-to-be-listed).

2024-08-14 07:16 UTC, closed without merging