Adding eThorp as Commercial Support
apache/guacamole-website pull request #152
Opened 2024-11-19 22:55 UTC by WalterSchnuble

I would like to add eThorp Technology as a commercial support resource for the Apache Guacamole project.

eThorp Technology offering Apache Guacamole support in Brazilian Portuguese, providing installation, configuration, optimization, and continuous maintenance to ensure a stable and secure remote desktop experience for businesses seeking reliable DaaS solutions

All the best !

Walter Schnuble

2024-11-19 23:10 UTC, mike-jumper requested changes
Please also combine these commits into a single, logical commit that describes the high-level nature of the changes being made:

![List of three commits, showing unfortunately vague commit messages](https://github.com/user-attachments/assets/a43110be-aa38-42e1-935c-62b869742e55)

The title of this PR is a decent example of such a high-level message.

2024-11-19 23:10 UTC, mike-jumper commented on _companies/ethorp.md
> +eThorp Technology offering Apache Guacamole support in Brazilian Portuguese, providing installation, configuration, optimization, and continuous maintenance to ensure a stable and secure remote deskt
I think you probably mean "offers" here (instead of "offering").

2024-11-19 23:22 UTC, WalterSchnuble commented on _companies/ethorp.md
> +eThorp Technology offering Apache Guacamole support in Brazilian Portuguese, providing installation, configuration, optimization, and continuous maintenance to ensure a stable and secure remote deskt
Correct. My apologies.
Should we update and make a new pull request?

2024-11-19 23:29 UTC, mike-jumper commented on _companies/ethorp.md
> +eThorp Technology offering Apache Guacamole support in Brazilian Portuguese, providing installation, configuration, optimization, and continuous maintenance to ensure a stable and secure remote deskt
Sure, or you can force push to the branch on your fork and it'll get picked up by this existing pull request.

2024-11-19 23:41 UTC, WalterSchnuble reviewed
Done

2024-11-20 12:05 UTC, necouchman commented
Closed by #153.

2024-11-20 12:05 UTC, closed without merging